# Generated by Django 3.2.6 on 2021-08-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20210809_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
