# Generated by Django 3.2.6 on 2021-08-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='banco',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
