# Generated by Django 3.2.6 on 2021-08-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20210809_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateTimeField(null=True),
        ),
    ]
