# Generated by Django 3.2.6 on 2021-08-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
    ]
