# Generated by Django 3.2.6 on 2021-08-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_remove_cliente_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='modified',
        ),
    ]
