# Generated by Django 3.2.6 on 2021-08-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='banco',
            field=models.CharField(choices=[('Bancolombia', 'Bancolombia'), ('BBVA', 'BBVA')], max_length=20, null=True),
        ),
    ]
