# Generated by Django 3.2.6 on 2021-08-09 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
        ('creditos', '0002_credito_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bancos.banco'),
        ),
    ]
